In [3]:
#1 creating arrays from list or tuples
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [9]:
#using numpy.zeros()
arr_zeros = np.zeros(5)
print(arr_zeros)
arr_zeros_2d = np.zeros((3, 4))
print(arr_zeros_2d)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
#using numpy.ones()
arr_ones = np.ones(5)
print(arr_ones)
arr_ones_2d = np.ones((3, 4))
print(arr_ones_2d)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
#using numpy.full()
arr_full = np.full(5, 7)
print(arr_full)
arr_full_2d = np.full((3, 3), 9)
print(arr_full_2d)

[7 7 7 7 7]
[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [15]:
#using numpy.arrange()
arr_arange = np.arange(10)
print(arr_arange)
arr_arange_step = np.arange(0, 10, 2)
print(arr_arange_step)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [17]:
#using numpy.linspace()
arr_linspace = np.linspace(0, 1, 5)
print(arr_linspace)

[0.   0.25 0.5  0.75 1.  ]


In [19]:
#using numpy.random functions
arr_rand_int = np.random.randint(0, 10, size=5)
print(arr_rand_int)

[7 8 0 5 2]


In [21]:
#random floats(uniform distribution)
arr_rand_float = np.random.rand(3, 4)
print(arr_rand_float)

[[0.61235294 0.92499004 0.97643824 0.42112038]
 [0.92656636 0.45324716 0.8673575  0.25985903]
 [0.7086854  0.1634539  0.37272108 0.96940143]]


In [23]:
#random floats(normal distribution)
arr_rand_normal = np.random.randn(3, 4)
print(arr_rand_normal)

[[-1.67455338 -0.71843714 -0.05084553  0.16172005]
 [-1.16350732  1.50378196 -1.18740274  0.00776433]
 [-0.44298556  1.13474186 -3.05646655  1.09242192]]


In [25]:
#using numpy.identity()
arr_identity = np.identity(3)
print(arr_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
#using numpy.copy()
arr_copy = np.array([1, 2, 3])
arr_copy2 = np.copy(arr_copy)
print(arr_copy2)

[1 2 3]


In [31]:
#2 manipulating arrays
#reshaping arrays
import numpy as np
arr = np.arange(12)
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
#Flattening arrays
arr_2d = np.array([[1, 2], [3, 4]])
flattened_arr = arr_2d.flatten()
print(flattened_arr)
ravelled_arr = arr_2d.ravel()
print(ravelled_arr)

[1 2 3 4]
[1 2 3 4]


In [35]:
#transposing arrays
arr_2d = np.array([[1, 2], [3, 4]])
transposed_arr = arr_2d.T
print(transposed_arr)

[[1 3]
 [2 4]]


In [37]:
#adding or removing dimensions
arr = np.array([1, 2, 3])
arr_2d = arr[:, np.newaxis]
print(arr_2d)
arr_squeezed = np.array([[[1], [2], [3]]])
arr_squeezed = np.squeeze(arr_squeezed)
print(arr_squeezed)

[[1]
 [2]
 [3]]
[1 2 3]


In [39]:
#aggregating arrays
arr = np.array([1, 2, 3, 4, 5])
sum_arr = np.sum(arr)  # Sum of elements
mean_arr = np.mean(arr)  # Average of elements
prod_arr = np.prod(arr)  # Product of elements
print(sum_arr, mean_arr, prod_arr)

15 3.0 120


In [41]:
#maximum and minimum
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
min_val = np.min(arr_2d)
max_val = np.max(arr_2d)
min_val_axis0 = np.min(arr_2d, axis=0)
max_val_axis1 = np.max(arr_2d, axis=1) 
print(min_val, max_val, min_val_axis0, max_val_axis1)

1 6 [1 2 3] [3 6]


In [43]:
#combining arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

concat_arr = np.concatenate([arr1, arr2]) 
print(concat_arr)

arr_2d_1 = np.array([[1, 2], [3, 4]])
arr_2d_2 = np.array([[5, 6], [7, 8]])

concat_2d = np.concatenate([arr_2d_1, arr_2d_2], axis=0)
print(concat_2d)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [45]:
#stacking arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

vstack_arr = np.vstack([arr1, arr2])
hstack_arr = np.hstack([arr1, arr2])
print(vstack_arr)
print(hstack_arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [47]:
#splitting arays
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 3)  # Split into 3 sub-arrays
print(split_arr)
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vsplit_arr = np.vsplit(arr_2d, 3)  # Split 2D array vertically
print(vsplit_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [49]:
#broadcasting
arr1 = np.array([1, 2, 3])
arr2 = np.array([[10], [20], [30]])

broadcasted_arr = arr1 + arr2
print(broadcasted_arr)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [3]:
#3 vectorization
import numpy as np
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
result = []
for i in range(len(A)):
    result.append(A[i] + B[i])
print(result)

[5, 7, 9]


In [5]:
#combining broadcasting and vectorization
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
vector = np.array([1, 1, 1])
result = matrix + vector
print(result)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
